### ISSUE TITLE
Color camera debayer problem

### ISSUE THREAD

**Issue by universe241981** [GuLinux/AstroPhoto-Plus#122]
Camera: QHY5P-II-C
Sample FITS image: [https://drive.google.com/file/d/148NNvzWvywuua_-ix-omixPRMTjdvWcu/view?usp=sharing](url)

The FITS image look good but when display as jpg in the web interface, it not good.

[log.txt](https://github.com/GuLinux/AstroPhoto-Plus/files/2897912/log.txt)
[fits-header.txt](https://github.com/GuLinux/AstroPhoto-Plus/files/2897913/fits-header.txt)

**Comment by GuLinux** [comment]
Thanks, I found the root cause in a bad data management in 8bit mode (which I very rarely use).
I need a bit of time to fully verify the fix works in both 8bit and 16bit mode, in the meantime I would recommend using 16bit only until this gets fixed.
Cheers,
Marco

**Comment by universe241981** [comment]
16 bit mean select png format instead of jpg format?

**Comment by GuLinux** [comment]
Hi,
No, it's a camera control, I believe it should be found under the `Controls` group of the INDI control panel for the camera

**Comment by GuLinux** [comment]
Sorry, haven't had time to check on my camera :(
There should be a "Format" INDI switch, you can see an example here:
https://goo.gl/images/z47et5

**Comment by GuLinux** [comment]
Hi, please have a go at testing the new version, you can just run the auto updater, and verify that the build version is 640, or just download the package for said build from here: https://astrophotoplus.gulinux.net/development-builds

**Comment by universe241981** [comment]
Hi,
I have update the build to version 640 by download the package.
Initially, I tried to update via auto updater in the web interface but failed. Then only use the downloaded package for update.
Everything work fine now.
Thank you.
