### ISSUE TITLE
Waiting for backend server to be ready...

### ISSUE THREAD

**Issue by universe241981** [GuLinux/AstroPhoto-Plus#123]
Usually how long it need to be wait? 
What cause the long wait?
As of the moment i writing this, it still "Waiting for backend server to be ready..."
Thanks.

[APP installation.txt](https://github.com/GuLinux/AstroPhoto-Plus/files/2898913/APP.installation.txt)
[APP installation 2.txt](https://github.com/GuLinux/AstroPhoto-Plus/files/2898914/APP.installation.2.txt)

**Comment by GuLinux** [comment]
On a slow machine (like the raspberry pi for instance, or even worse the Pi Zero) it can take quite a lot, as it has to install all the python dependencies, and compile native modules.
I'm not sure how long, but it might even be more than half hour on a slow system.
You can check the backend status by running
```AstroPhotoPlus-ctl logs```

**Comment by universe241981** [comment]
It seem that not possible to setup in Pi0W...?
[Pi0W setup_not complete.txt](https://github.com/GuLinux/AstroPhoto-Plus/files/2903899/Pi0W.setup_not.complete.txt)
