### ISSUE TITLE
phd2 connection

### ISSUE THREAD

**Issue by dragonlost** [GuLinux/AstroPhoto-Plus#140]
Hello. 
is it expected to connect phd2 to allow dithering (with phd2 server connection) ?
 thank you.

**Comment by GuLinux** [comment]
Hi,
not yet unfortunately.
I've just started implementing an autoguiding solution (without PHD2, but using [Donuts](https://github.com/jmccormac01/Donuts), a quite promising autoguiding algorithm), but it's still gonna be a while until I have a testable beta. It will of course also allow dithering.

I'm also thinking of allowing user to configure either the internal Donuts based autoguider, or PHD2 as an alternative, but if I'll do so it's gonna be a very simple integration (users will be expected to start and configure PHD2 on their own, AstroPhoto Plus will just connect and dither when necessary).

What are your thoughts on this? I might need an early beta tester when autoguiding will be implemented, would you be available for that?
Cheers,
Marco

**Comment by dragonlost** [comment]
Ha super! That's exactly what I was hoping for!
I do not mind configuring phd2 by hand.

I am a developer on the NAFABox project. And we would like to integrate your software in!

**Comment by dragonlost** [comment]
I am already beta tester for other software that integrates so no problem.

**Comment by GuLinux** [comment]
Interesting project, I think we should really think on cooperating more :)
As you see I already tried to create a minimal ready-to-go raspberry pi image, so I guess we're heading in the same direction :)

I think I can get the PHD2 integration relatively quickly, possibly by the end of this week. It's gonna be just a simple control panel with `Connect/Disconnect`, `Start/Stop guiding`, possibly `Train`, and the dither options in the sequence job (`on/off`, `pixels`).

Sounds good?

**Comment by dragonlost** [comment]
yes is very good !

The goal of NAFABox is to be a box for nomad astronomy. So your solution is ideal.
The EKOS Live solution is good too but is not suitable for use on nomad (without internet).
