### ISSUE TITLE
hostapd service failed after update APP from b621 to b666

### ISSUE THREAD

**Issue by universe241981** [GuLinux/AstroPhoto-Plus#143]
hostapd.service: Failed to load environment files: No such file or directory
Failed to start Advanced IEEE 802.11 AP and IEEE 802.1X/WPA/WPA2/EAP Authenticator

The `/etc/default/hostapd` -> `/usr/share/AstroPhotoPlus/config/raspberry_pi/hostapd`
But such file does not exist.

The same goes to `/etc/hostapd`

Device: RPi3b
Download APP Raspberry image from website. Image version b621 dated 16.02.2019.
After initial power on, system update then follow by APP update.

**Comment by universe241981** [comment]
I think the Raspberry image download link on the official website need to be update to the latest image with date 2019-03-18.
That will eliminate most of the problem and avoid issue from future user that try to update the image from b622 to b666.

**Comment by GuLinux** [comment]
Closing, as with the new version hostapd is not used anymore, AstroPhoto Plus fully switched to NetworkManager
