### ISSUE TITLE
ubuntu.sh doesn't install indi

### ISSUE THREAD

**Issue by franky384** [GuLinux/AstroPhoto-Plus#146]
**Describe the bug**
When i run your script i see that package indi-full not found
i also see:

Using nginx as web server
'/usr/lib/AstroPhotoPlus/frontend/webserver-conf/nginx/astrophotoplus.conf' -> '/etc/nginx/sites-available/astrophotoplus.conf'
Failed to execute operation: Too many levels of symbolic links

is this an error or can i ignore this ?

**To Reproduce**
1. run your install script
2  See error

**Expected behavior**
add apt-get update after adding the indi repository in your ubunt.sh install script:

setup-indi-ppa() {
    notify "Adding INDI stable PPA"
    add-apt-repository -y ppa:mutlaqja/ppa
    **apt-get update**
    notify "Installing INDI full"
    apt-get install -y -q indi-full

**Screenshots**

**Server Information**
- AstroPhoto Plus Version newest
 - Server hardware odroid u3
 - Operating system (e.g. Ubuntu mate 16.04)
 - Python version in use
 - Remember to attach server logs created with `AstroPhotoPlus-ctl logs` if applicable.

**Comment by GuLinux** [comment]
Hi, thanks for the report.
Just fixed in latest master.
Cheers,
Marco
