### ISSUE TITLE
Backend server never gets ready

### ISSUE THREAD

**Issue by franky384** [GuLinux/AstroPhoto-Plus#147]
**Describe the bug**
I wait since 2 hours, it never finishes building the backend.
ERROR: setuptools 30.3 or later is required by astropy-helpers

**To Reproduce**
1. run ubuntu.sh

**Expected behavior**
Build backend

[astrophotoplus.txt](https://github.com/GuLinux/AstroPhoto-Plus/files/3304664/astrophotoplus.txt)
**Server Information**
- AstroPhoto Plus Version 671
 - Server hardware type ARM device Odroid U3
 - Operating system Ubuntu Mate 16.04)
 - Python version in use 3.5
 - Remember to attach server logs created with `AstroPhotoPlus-ctl logs` if applicable.

**Comment by GuLinux** [comment]
Hi, closing as this should now be properly fixed in recent build.
