### ISSUE TITLE
Polar alignment

### ISSUE THREAD

**Issue by mireianievas** [GuLinux/AstroPhoto-Plus#148]
Very interesting project.
Would it be feasible to have a polar alignment routine similar to the one of Ekos using plate solves and moving the mount between them?

**Comment by mireianievas** [comment]
Ok, I see it was discussed https://github.com/GuLinux/AstroPhoto-Plus/issues/31 . Closing this.

**Comment by GuLinux** [comment]
Hi, thanks!
It's not exactly "discussed", but just planned, I use github issues to raise tickets to myself.

Hopefully this should come right after autoguiding (which shouldn't take too long, just need to cut myself some time to finish it).

Cheers,
Marco
