### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by gehelem** [GuLinux/AstroPhoto-Plus#178]
Hi
Sorry to report this here, but https://astrophotoplus.gulinux.net/ is down at the moment
This is what i get :
![image](https://user-images.githubusercontent.com/20287008/74536143-c3809180-4f37-11ea-8861-bbef545000e6.png)

=> No other possibilities to find install instructions...

Gilles.

**Comment by GuLinux** [comment]
Hi,
thanks for noticing, it should up and running now :+1:

**Comment by gehelem** [comment]
great, thanks a lot
