### ISSUE TITLE
Raspberry Pi 4B

### ISSUE THREAD

**Issue by ettoreribaudo** [GuLinux/AstroPhoto-Plus#196]
The software function with PI 4B or not?

**Comment by GuLinux** [comment]
It does, yes, I have one in my desk right now.
Just make sure you try the latest build.
At the moment the precompiled Raspbian image is way outdated, so I'd recommend getting the `deb` package instead.
Updating the raspbian image is the next thing on my list though.

Closing as it's not an issue.
Cheers!
