### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by ettoreribaudo** [GuLinux/AstroPhoto-Plus#203]
If possible to insert for future release upgrade directly?
Ettore

**Comment by GuLinux** [comment]
Hi,
Sorry, I didn't understand the question.. do you mean if it is possible to upgrade from within the app itself?

It is already, yes. In the settings page there should be an option for upgrading.

**Comment by ettoreribaudo** [comment]
Thanks i see.
I had to install it again but then it has random problems.
