### ISSUE TITLE
Astrometry

### ISSUE THREAD

**Issue by ettoreribaudo** [GuLinux/AstroPhoto-Plus#213]
Why not upload catalogs directly to sd for astrometry?

**Comment by GuLinux** [comment]
Hi,
Sorry, what do you mean exactly? Do you mean the astrometry index files, or the NGC/IC/Messier database?

And by "directly to sd", do you mean as in "user can download manually and save them into the SD"?

**Comment by ettoreribaudo** [comment]
> Hi,
> Sorry, what do you mean exactly? Do you mean the astrometry index files, or the NGC/IC/Messier database?
> 
> And by "directly to sd", do you mean as in "user can download manually and save them into the SD"?

Sorry, what do you mean exactly? Do you mean the astrometry index files, or the NGC/IC/Messier database? **Astrometry for plate solve**r

And by "directly to sd", do you mean as in "user can download manually and save them into the SD"? **in directory in to Sd Card**

**Comment by GuLinux** [comment]
I guess I could add a setting to change the location of plate solving index files, is that what you meant?

**Comment by ettoreribaudo** [comment]
I mean if it is possible to load the Ucac3 catalog in a resident way

**Comment by GuLinux** [comment]
Yes, possibly (I need to look up where to find it), but that's a different things from astrometry indexes though

**Comment by GuLinux** [comment]
I'll close this for now, as extra catalog can now be accessed through SIMBAD ( #235 )
