### ISSUE TITLE
Make Indi install optional

### ISSUE THREAD

**Issue by tkottary** [GuLinux/AstroPhoto-Plus#222]
**Is your feature request related to a problem? Please describe.**
I already have indi nightly installed and do not want to install the stable version

**Describe the solution you'd like**
give option to skip indi installation 

**Describe alternatives you've considered**
re-install indi nightly after astrophotoplus is installed.

**Additional context**

**Comment by GuLinux** [comment]
Hi,
sorry, do you mean in the "easy install" script?
If that's the case, I'd rather leaving it as it is, as I feel the aim should be to ask as less questions as possible, and INDI per se is not really an "optional" component to which a regular user would likely say "no".

For advanced installation, there's always the option of installing the `.deb` package manually, which only depends on `libindi-dev` (which I guess should be available in INDI nightly as well) and then manually running `AstroPhotoPlus-ctl autosetup`

**Comment by GuLinux** [comment]
(closing unless clarified otherwise)
