### ISSUE TITLE
Version mismach

### ISSUE THREAD

**Issue by ettoreribaudo** [GuLinux/AstroPhoto-Plus#224]
This a error?

<img width="1680" alt="Schermata 2020-05-30 alle 21 00 39" src="https://user-images.githubusercontent.com/21957407/83337070-c326bf00-a2b8-11ea-803a-3d7d223fbe6a.png">

**Comment by GuLinux** [comment]
Hi, not exactly, it's just a warning that you've updated the backend, so you need to reload the app (refreshing the browser), as written in the notification.

I tried to implement an automatic update, but it was too unstable, so I left it up to the user to reload the frontend.
