### ISSUE TITLE
Canon 1300D pixel

### ISSUE THREAD

**Issue by ettoreribaudo** [GuLinux/AstroPhoto-Plus#225]
There are some errors, the Canon has 14 bits with 5184 x 3456 4.3 pixels, but the data is wrong and any value that I put them back is wrong.
<img width="1680" alt="Schermata 2020-05-31 alle 17 08 46" src="https://user-images.githubusercontent.com/21957407/83355710-8bc01d00-a361-11ea-8ccd-46c9549933be.png">
<img width="1680" alt="Schermata 2020-05-31 alle 16 59 23" src="https://user-images.githubusercontent.com/21957407/83355714-8e227700-a361-11ea-80e4-14e574136898.png">

**Comment by ettoreribaudo** [comment]
Now the log gives me this error, after update ver 911 with Canon 
Aug 31 18:53:50 raspberrypi sudo [3944]: pam_unix (sudo: session): session closed for user root
May 31 18:53:50 raspberrypi sudo [3954]: pi: TTY = unknown; PWD = / usr / lib / AstroPhotoPlus / backend; USER = root; COMMAND = / usr / lib / AstroPhotoPlus / backend / network / network_manager.py active-connections --json
May 31 18:53:50 raspberrypi sudo [3954]: pam_unix (sudo: session): session opened for user root by (uid = 0)
May 31 18:53:50 raspberrypi sudo [3954]: pam_unix (sudo: session): session closed for user root
May 31 18:53:51 raspberrypi AstroPhoto-Plus [460]: INDI server localhost / 7624 disconnected.
May 31 18:53:51 raspberrypi AstroPhoto-Plus [460]: INDI server localhost / 7624 disconnected.
May 31 18:53:51 raspberrypi AstroPhoto-Plus [460]: [2020-05-31 18:53:51 +0200] [626] [WARNING] BLOBClient: Unexpected disconnection from INDI server with error code -1, trying to connect
May 31 18:53:51 raspberrypi sudo [3979]: pi: TTY = unknown; PWD = / usr / lib / AstroPhotoPlus / backend; USER = root; COMMAND = / usr / lib / AstroPhotoPlus / backend / network / network_manager.py connections --json
May 31 18:53:51 raspberrypi sudo [3979]: pam_unix (sudo: session): session opened for user root by (uid = 0)
May 31 18:53:51 raspberrypi sudo [3979]: pam_unix (sudo: session): session closed for user root
May 31 18:53:51 raspberrypi sudo [3990]:

**Comment by ettoreribaudo** [comment]
I resolved see the canon but not bit and pixel.

**Comment by GuLinux** [comment]
Hi,
this is already planned as #211 .
INDI doesn't seem to be capable of getting DSLR information, there isn't much I can do on AstroPhoto Plus, except implementing a wizard asking the user to manually store camera information (which is what #211 is about).

An alternative could also be to implement a "Camera database" with all these infos, but I don't see this as a viable alternative in the near future.
