### ISSUE TITLE
lighttpd  instead of nginx? 

### ISSUE THREAD

**Issue by aruangra** [GuLinux/AstroPhoto-Plus#253]
Is it possible to run Astrophoto plus with lighttpd instead of nginx? 
Thanks.

**Comment by gstrauss** [comment]
After looking at `config/dev-webserver-conf/nginx/astrophotoplus.conf`, a lighttpd equivalent might be as simple as this (untested):
```
server.port = 3080
server.name = localhost
server.max-request-size = 204800
server.max-write-idle = 65535
server.stream-response-body = 2
server.modules += ("mod_setenv", "mod_proxy")
setenv.set-response-header = (
  "Cache-Control" => "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
)
proxy.server = (
  ""     => ( ( "host" => "127.0.0.1", "port" => "3000" ) )
  "/api" => ( ( "host" => "127.0.0.1", "port" => "5000" ) )
)
```
However, `proxy.header` might need to be added if URL-mapping is needed between the request and the backend.

**Comment by GuLinux** [comment]
Hi,
closing as this is not really relevant to AstroPhoto Plus.
Any HTTP server would work, providing it's properly configured, including lighttpd.
The configuration provided from @gstrauss looks correct to me.
Thanks
